[package]
name = "advent_of_code_2018"
version = "0.1.0"
authors = ["Jakub Jaroszewski <jakub.jaroszewski@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.0"
regex = "1.1.0"
text_io = "0.1.7"
