[package]
name = "advent_of_code_2018"
version = "0.1.0"
authors = ["Jakub Jaroszewski <jakub.jaroszewski@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.8.4"
regex = "1.5.4"
text_io = "0.1.9"
